Repository sandialabs/firewheel, pull requests merged in 2025-02, with the labels that each got.

#50 feat: resolve #33 by enhancing the 'dry-run' flag
  src/firewheel/cli/helpers/experiment
  src/firewheel/control/model_component_manager.py
Labels: enhancement

#62 ci: Add new CI actions to autotag PRs and update release notes and changelog entries
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/pr-title-checker.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/update-changelog.yaml
  CHANGELOG.md
  CONTRIBUTING.rst
Labels: ci

#48 refactor: Replace the gRPC-backed RepositoryDB with a JSON-file backed one.
  docs/source/_static/proto_doc.html
  docs/source/code/lib.rst
  pyproject.toml
  src/firewheel/control/repository_db.py
  src/firewheel/lib/grpc/firewheel_grpc.proto
  src/firewheel/lib/grpc/firewheel_grpc_client.py
  src/firewheel/lib/grpc/firewheel_grpc_pb2.py
  src/firewheel/lib/grpc/firewheel_grpc_pb2.pyi
  src/firewheel/lib/grpc/firewheel_grpc_pb2_grpc.py
  src/firewheel/lib/grpc/firewheel_grpc_server.py
  src/firewheel/tests/unit/control/test_external_order.py
  src/firewheel/tests/unit/control/test_graph_object_depends.py
  src/firewheel/tests/unit/control/test_graph_object_load.py
  src/firewheel/tests/unit/control/test_graph_object_recursive_depends.py
  src/firewheel/tests/unit/control/test_mcm_circular_dependency.py
  src/firewheel/tests/unit/control/test_mcm_defaults.py
  src/firewheel/tests/unit/control/test_mcm_dependency_graph.py
  src/firewheel/tests/unit/control/test_mcm_experiment_graph.py
  src/firewheel/tests/unit/control/test_mcm_precedes.py
  src/firewheel/tests/unit/control/test_mcm_process_model_component.py
  src/firewheel/tests/unit/control/test_mcm_recursive_mc_depends.py
  src/firewheel/tests/unit/control/test_model_component.py
  src/firewheel/tests/unit/control/test_model_component_dependency_graph.py
  src/firewheel/tests/unit/control/test_model_component_image_upload.py
  src/firewheel/tests/unit/control/test_model_component_vm_resource_upload.py
  src/firewheel/tests/unit/control/test_plugin_arguments.py
  src/firewheel/tests/unit/control/test_plugin_load.py
  src/firewheel/tests/unit/control/test_repository_db.py
  src/firewheel/tests/unit/control/test_require_class.py
  src/firewheel/tests/unit/test_utils.py
  tox.ini
Labels: refactor

#66 ci: Enhance CI reusability
  .github/workflows/documentation.yml
  .github/workflows/linting.yml
  .github/workflows/testing.yml
  CONTRIBUTING.rst
Labels: ci
