Repository sandialabs/firewheel, pull requests merged in 2025-05, with the labels that each got.

#114 fix: Clearly delineate between editable/non-editable MC installs
  docs/source/install/install.rst
  install.sh
Labels: fix, documentation

#127 chore: Tightening dependencies to address python 3.8 support
  install.sh
  pyproject.toml
  tox.ini
Labels: chore

#81 fix: Ensuring users know when a duplicate repository is trying to be added
  src/firewheel/cli/helpers/repository/install
  src/firewheel/control/repository_db.py
  src/firewheel/tests/unit/control/test_repository_db.py
Labels: fix

#128 feat(cli): Adding a new firewheel config edit command
  docs/source/cli/commands.rst
  docs/source/cli/helper_docs.rst
  src/firewheel/cli/configure_firewheel.py
  src/firewheel/tests/unit/cli/test_cli_configure.py
Labels: documentation, feature

#130 chore: Remove duplicate pip installation instruction
  install.sh
Labels: chore
