Repository sandialabs/firewheel, pull requests merged in 2025-04, with the labels that each got.

#104 ci: Fix pydocstyle version to prevent linting errors
  tox.ini
Labels: fix, ci

#108 ci: Update the GitLab CI file to work with new paths
  .gitlab-ci.yml
Labels: ci

#102 test: Use mock for simulating permissioned systems
  src/firewheel/tests/unit/control/test_repository_db.py
Labels: test

#109 ci: Updating the discovery link to an official release.
  .github/actions/prepare-discovery/action.yml
Labels: ci

#112 feat: Docker firewheel ssh
  docker/firewheel.dockerfile
  docker/fsroot/usr/bin/scp
  docker/fsroot/usr/bin/ssh
  docker/fsroot/usr/local/bin/entry
Labels: feature

#118 docs: Fixing docker README about ssh and scp being overwritten
  docker/README.md
Labels: documentation

#117 fix: Not sleeping for infinity in docker container
  docker/fsroot/usr/local/bin/entry
Labels: fix
