Repository sandialabs/firewheel, pull requests merged in 2025-03, with the labels that each got.

#76 fix: Correct behavior of the SSH Manager for quoted strings
  src/firewheel/cli/ssh_manager.py
  src/firewheel/tests/unit/cli/test_ssh_manager.py
Labels: fix

#77 fix: fixing quoted expansion of FIREWHEEL_NODES variable in install.sh
  install.sh
Labels: fix

#70 fix: Making adjustments to the tab completion to work with `/bin/sh`
  src/firewheel/cli/completion/completion-template.sh
Labels: fix

#69 ci: Updating CI to use specific tagged versions of github actions and minimizing/enforcing permissions for all actions.
  .github/workflows/linting.yml
  .github/workflows/pr-title-checker.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/testing.yml
  .github/workflows/update-changelog.yaml
Labels: ci, security

#68 feat: Create a initial docker container for FIREWHEEL
  .github/workflows/docker.yml
  docker/README.md
  docker/firewheel.dockerfile
  docker/fsroot/etc/default/minimega
  docker/fsroot/root/.tmux.conf
  docker/fsroot/start-minimega.sh
  docker/fsroot/usr/bin/chgrp
  docker/fsroot/usr/bin/scp
  docker/fsroot/usr/bin/ssh
  docker/fsroot/usr/bin/sudo
  docker/fsroot/usr/local/bin/entry
  docs/source/install/docker.md
  docs/source/install/index.rst
Labels: documentation, feature

#80 fix: Fixing a bug where the model components are both cloned and pip installed leading to duplication.
  install.sh
Labels: fix

#84 doc: Adding a reference to Cyberwheel
  README.rst
Labels: documentation

#85 fix: Fixing the paths to various model components via the install script
  install.sh
Labels: fix

#86 ci: Clean up GitLab CI and reduce duplicate code
  .gitlab-ci.yml
Labels: ci

#65 fix: Address adding duplicate repositories and conflicts with manual vs package installed repositories.
  src/firewheel/control/repository_db.py
  src/firewheel/tests/unit/control/test_repository_db.py
Labels: fix, test

#92 ci: fixing an issue where checking for labels fails
  .github/workflows/docker.yml
  .github/workflows/release-drafter.yml
Labels: fix, ci

#93 ci: adjusting the PR label checking to a working version
  .github/workflows/release-drafter.yml
Labels: fix, ci

#94 ci: Run PR label check only in pull request contexts
  .github/workflows/release-drafter.yml
Labels: ci
