Repository sandialabs/firewheel, pull requests merged in 2025-09, with the labels that each got.

#157 fix: Expand docker variables and fix discovery path
  docker/firewheel.dockerfile
  docker/fsroot/usr/local/bin/entry
Labels: fix

#154 ci: generate static webpage for performance testing
  .gitlab-ci.yml
Labels: ci

#161 fix: Address repository installation short circuit
  src/firewheel/cli/helpers/repository/install
Labels: fix

#162 ci: Updating the GitLab CI for ansible usage
  .gitlab/ci/setup.yml
Labels: ci

#174 refactor: Adding some consistency to github actions file extensions
  .github/workflows/pr-title-checker.yml
  .github/workflows/update-changelog.yml
Labels: refactor

#167 feat: Add a CLI command for getting the configuration path
  src/firewheel/cli/configure_firewheel.py
  src/firewheel/tests/unit/cli/test_cli_configure.py
Labels: feature

#165 chore: Remove code for building wheel in favor of CI deployments
  install.sh
Labels: chore

#182 fix: Addressing an issue with quotations appearing in the docker environment variables
  docker/fsroot/start-minimega.sh
Labels: fix

#186 ci: Add flexibility to GitLab CI
  .gitlab-ci.yml
Labels: ci

#191 chore: Updating the dependabot limit on open PRs
  .github/dependabot.yml
Labels: chore
